kitchen_light_off:
  sequence:
  - service: notify.righteye
    data:
      title: "Home Assistant"
      message: "Turning off Kitchen Lights!"
      data:
        icon: "info"
        displaytime: 20000
  - service: light.turn_off
    data:
      entity_id: group.kitchen_lights