light_on_notify_lefteye:
  sequence:
  - service: notify.lefteye
    data:
      title: "Home Assistant"
      message: "Turning on Livingroom Lights!"
      data:
        icon: "info"
        displaytime: 20000
  - service: light.turn_on
    data:
      color_name: white
      brightness: 255
      entity_id: group.livingroom_lights
  - service: switch.turn_on
    entity_id: switch.ge_12727_inwall_smart_switch_toggle_switch_2