light_color_notify_lefteye:
  sequence:
  - service: notify.lefteye
    data:
      title: "Home Assistant"
      message: "Change Livingroom Lights Color {{ color_profile }}!"
      data:
        icon: "info"
        displaytime: 20000
  - service: light.turn_on
    data:
      profile: "{{ color_profile }}"
#      brightness: 254
      entity_id: group.livingroom_lights