light_off_notify_righteye:
  sequence:
  - service: notify.righteye
    data:
      title: "Home Assistant"
      message: "Turning off Bedroom Lights!"
      data:
        icon: "info"
        displaytime: 20000
  - service: light.turn_off
    data:
      entity_id: group.bedroom_lights