light_on_notify_righteye:
  sequence:
  - service: notify.righteye
    data:
      title: "Home Assistant"
      message: "Turning on Bedroom Lights!"
      data:
        icon: "info"
        displaytime: 20000
  - service: light.turn_on
    data:
      color_name: white
      brightness: 255
      entity_id: group.bedroom_lights