light_color_notify_righteye:
  sequence:
  - service: notify.righteye
    data_template:
      title: "Home Assistant"
      message: "Change Bedroom Lights Color- '{{ color_profile }}'!"
      data:
        icon: "info"
        displaytime: 20000
  - service: light.turn_on
    data_template:
#      profile: red
      profile: '{{ color_profile }}'
#      brightness: 255
      entity_id: group.bedroom_lights