- alias: "All Lights - Voice Change On"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/all/lights_on
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Turning On All Lights!"
    - service: light.turn_on
      entity_id: group.all_lights

- alias: "All Lights - Voice Change Off"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/all/lights_off
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Turning Off All Lights!"
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: switch.ge_12727_inwall_smart_switch_toggle_switch_2_0
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_bedroom
        option: 'OFF'
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_livingroom
        option: 'OFF'
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_kitchen
        option: 'OFF'
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_bathroom
        option: 'OFF'

- alias: "All Lights - Voice Change Color"
  hide_entity: true
  trigger:
    - platform: mqtt
      topic: voice/all/lights_color
    - platform: mqtt
      topic: voice/all/lights_scene
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Changing Color of All Lights!"
    - service: light.turn_on
      data_template:
        profile: "{{ trigger.payload }}"
        entity_id: group.all_lights