- alias: "All Lights - Voice Change On"
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: voice/all/lights_on
  action:
    - service: light.turn_on
      entity_id: group.all_lights

- alias: "All Lights - Voice Change Off"
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: voice/all/lights_off
  action:
    - service: script.turn_on
      data:
        entity_id: script.all_lights_off

- alias: "All Lights - Voice Change Color"
  initial_state: 'true'
  trigger:
    - platform: mqtt
      topic: voice/all/lights_color
    - platform: mqtt
      topic: voice/all/lights_scene
  action:
    - service: light.turn_on
      data_template:
        profile: "{{ trigger.payload }}"
        entity_id: group.all_lights
