- alias: "Bathroom Motion On (Night)"
  initial_state: 'true'
#  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_bathroom_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.bathroom_light_dim
        state: 'on'
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.timed_bathroom_nightlight

- alias: "Bathroom Motion On (Day)"
  initial_state: 'true'
#  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_bathroom_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.bathroom_light_dim
        state: 'off'
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.timed_bathroom_bright

- alias: "Toilet Motion On (Night)"
  initial_state: 'true'
#  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_toilet_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.bathroom_light_dim
        state: 'on'
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.timed_bathroom_nightlight

- alias: "Toilet Motion On (Day)"
  initial_state: 'true'
#  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_toilet_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.bathroom_light_dim
        state: 'off'
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.timed_bathroom_bright

- alias: "Early Bathroom Motion On"
  initial_state: 'true'
#  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_bathroom_early_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.bathroom_timer
        state: 'idle'
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Bathroom Early Motion!"
    - service: script.turn_on
      data:
        entity_id: script.timed_bathroom_early

- alias: "Turn Dim On"
  initial_state: 'true'
  trigger:
    platform: time
    at: '18:00:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bathroom_light_dim

- alias: "Turn Bright On"
  initial_state: 'true'
  trigger:
    platform: time
    at: '07:01:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bathroom_light_dim

- alias: Bathroom Early Timer Finished
  initial_state: 'true'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom_early_timer
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Bathroom Early Timer Finished!"
    - service: script.turn_on
      data:
        entity_id: script.bathroom_lights_off

- alias: Bathroom Timer Finished (Motion Detected)
  initial_state: 'true'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom_timer
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.aeotec_zw100_multisensor_bathroom_burglar
            state: '8'
          - condition: state
            entity_id: sensor.aeotec_zw100_multisensor_toilet_burglar
            state: '8'
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Bathroom Timer Finished! (Motion Detected)"
    - service: timer.start
      data:
        entity_id: timer.bathroom_timer

- alias: Bathroom Timer Finished (Motion Not Detected, Humidity Not Detected)
  initial_state: 'true'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom_timer
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
      - condition: state
        entity_id: sensor.aeotec_zw100_multisensor_bathroom_burglar
        state: '0'
      - condition: state
        entity_id: binary_sensor.bathroom_high_humidity
        state: 'off'
      - condition: state
        entity_id: sensor.aeotec_zw100_multisensor_toilet_burglar
        state: '0'
      - condition: state
        entity_id: binary_sensor.toilet_high_humidity
        state: 'off'
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Bathroom Timer Finished! (Motion Not Detected, Humidity Not Detected)"
    - service: script.turn_on
      data:
        entity_id: script.bathroom_lights_off

- alias: Bathroom Timer Finished (Motion Not Detected, Humidity Detected)
  initial_state: 'true'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom_timer
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: sensor.aeotec_zw100_multisensor_bathroom_burglar
                state: '0'
              - condition: state
                entity_id: binary_sensor.bathroom_high_humidity
                state: 'on'
          - condition: and
            conditions:
              - condition: state
                entity_id: sensor.aeotec_zw100_multisensor_toilet_burglar
                state: '0'
              - condition: state
                entity_id: binary_sensor.toilet_high_humidity
                state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Bathroom Timer Finished! (Motion Not Detected, Humidity Detected)"
    - service: timer.start
      data:
        entity_id: timer.bathroom_timer

- alias: "Toilet Motion Off"
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_toilet_burglar
    to: '0'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.sonoff_10006b80c3
    - service: timer.start
      data:
        entity_id: timer.bathroom_diffuser

- alias: Bathroom Diffuser Timer Finished
  initial_state: 'true'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom_diffuser_timer
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Bathroom Diffuser Timer Finished!"
    - service: switch.turn_off
      data:
        entity_id: switch.sonoff_10006b80c3