- alias: "Bathroom Motion On (Night)"
#  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_bathroom_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '17:00:00'
        before: '07:00:00'
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.timed_bathroom_nightlight

- alias: "Bathroom Motion On (Day)"
#  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_bathroom_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '07:01:00'
        before: '16:59:00'
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.timed_bathroom_bright

- alias: "Early Bathroom Motion On"
#  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_bathroom_early_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: script.bathroom_off_timer
        state: 'off'
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.timed_bathroom_early