- alias: "Bathroom Lights - Voice Change On"
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: voice/bathroom/lights_on
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_bathroom
        option: 'White'

- alias: "Bathroom Lights - Voice Change Off"
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: voice/bathroom/lights_off
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_bathroom
        option: 'OFF'

- alias: "Bathroom Lights - Voice Change Color/Scene"
  initial_state: 'true'
  trigger:
    - platform: mqtt
      topic: voice/bathroom/lights_color
    - platform: mqtt
      topic: voice/bathroom/lights_scene
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.scene_bathroom
        option: "{{ trigger.payload | title }}"

- alias: "Bathroom Lights - Voice Change Dim"
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: voice/bathroom/lights_adjust
    payload: 'dim'
  action:
    service: light.turn_on
    data_template:
      entity_id: group.bathroom_lights
      brightness: >
        {% if states('light.__level_6.brightness') | int > 200 %}
          150
        {% else %}
          50
        {% endif %}

- alias: "Bathroom Lights - Voice Change Bright"
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: voice/bathroom/lights_adjust
    payload: 'bright'
  action:
    service: light.turn_on
    data_template:
      entity_id: group.bathroom_lights
      brightness: >
        {% if states('light.__level_6.brightness') | int < 100 %}
          150
        {% else %}
          254
        {% endif %}
