- alias: Bathroom Lights - Adjust Brightness
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: input_number.bathroom_brightness
  action:
    - service: light.turn_on
      data_template:
        entity_id: group.bathroom_lights
        brightness: '{{ trigger.to_state.state | int }}'