- alias: "Shower Running (Bathroom Sensor)"
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_high_humidity
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.enable_bathroom_automation
    state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.timed_bathroom_bright

- alias: "Shower Running (Toilet Sensor)"
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_high_humidity
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.enable_bathroom_automation
    state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.timed_bathroom_bright
