- alias: "Bathroom Lights - Dash Change On"
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: dash2
    payload: 'active'
  action:
    - service: input_number.select_value
      data:
        entity_id: input_number.bathroom_brightness
        value: 255
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_bathroom
        option: 'White'
