- alias: "Bathroom Motion Detection On"
#  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.__sensor_5_0
    from: 'off'
    to: 'on'
  action:
    service: script.turn_on
    entity_id: script.timed_bathroom_nightlight