- alias: "Bathroom Motion On (Night)"
#  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_4_10
    from: '0'
    to: '8'
  condition:
    condition: time
    after: '17:00:00'
    before: '07:00:00'
  action:
    service: script.turn_on
    entity_id: script.timed_bathroom_nightlight

- alias: "Bathroom Motion On (Day)"
#  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_4_10
    from: '0'
    to: '8'
  condition:
    condition: time
    after: '07:01:00'
    before: '16:59:00'
  action:
    service: script.turn_on
    entity_id: script.timed_bathroom_bright

- alias: "Bathroom Motion Detection Off"
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_4_10
    from: '8'
    to: '0'
  action:
    service: script.turn_on
    entity_id: script.bathroom_off_timer