- alias: "Bathroom Motion On (Night)"
#  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_bathroom_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.bathroom_light_dim
        state: 'on'
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.timed_bathroom_nightlight

- alias: "Bathroom Motion On (Day)"
#  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_bathroom_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.bathroom_light_dim
        state: 'off'
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.timed_bathroom_bright

- alias: "Early Bathroom Motion On"
#  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_bathroom_early_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.bathroom_timer
        state: 'idle'
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Bathroom Early Motion!"
    - service: script.turn_on
      data:
        entity_id: script.timed_bathroom_early

- alias: "Turn Dim On"
  trigger:
    platform: time
    at: '18:00:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bathroom_light_dim

- alias: "Turn Bright On"
  trigger:
    platform: time
    at: '07:01:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bathroom_light_dim

- alias: Bathroom Early Timer Finished
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom_early_timer
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Bathroom Early Timer Finished!"
    - service: script.turn_on
      data:
        entity_id: script.bathroom_lights_off

- alias: Bathroom Timer Finished (Motion Detected)
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom_timer
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
      - condition: state
        entity_id: sensor.aeotec_zw100_multisensor_bathroom_burglar
        state: '8'
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Bathroom Timer Finished! (Motion Detected)"
    - service: timer.start
      data:
        entity_id: timer.bathroom_timer

- alias: Bathroom Timer Finished (Motion Not Detected)
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom_timer
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.enable_bathroom_automation
        state: 'on'
      - condition: state
        entity_id: sensor.aeotec_zw100_multisensor_bathroom_burglar
        state: '0'
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Bathroom Timer Finished! (Motion Not Detected)"
    - service: script.turn_on
      data:
        entity_id: script.bathroom_lights_off