- alias: "Getting Out Of Bed"
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.bed_pressure_left_sensor
    to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.lightstrip_3
        brightness: 255
        color_name: purple

- alias: "Getting Into Bed"
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.bed_pressure_left_sensor
    to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.lightstrip_3
