- alias: Bedroom Lights - Adjust Brightness
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: input_number.bedroom_brightness
  action:
    - service: light.turn_on
      data_template:
        entity_id: group.bedroom_lights
        brightness: '{{ trigger.to_state.state | int }}'