- alias: Bedroom Lights - Input Select Chagne Color
  trigger:
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Blue'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Red'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Pink'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Orange'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'White'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Purple'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Green'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Teal'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Aqua'
  action:
    - service: script.notify_kodi_frontends
      data_template:
        message: 'Changing Bedroom Lights to Scene: {{ states.input_select.scene_bedroom.state }} and Brightness: {{ states.input_slider.bedroom_brightness.state }}'
    - service: light.turn_on
      data_template:
        entity_id: group.bedroom_lights
        brightness: '{{ states.input_slider.bedroom_brightness.state | int }}'
        profile: "{{ states.input_select.scene_bedroom.state | lower }}"

- alias: Bedroom Lights - Input Select Chagne Scene
  trigger:
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Normal'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Movie'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Concentrate'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Energize'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Reading'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Relax'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Romantic'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Warm'
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'Stretch'
  action:
    - service: script.notify_kodi_frontends
      data_template:
        message: 'Changing Bedroom Lights to Scene: {{ states.input_select.scene_bedroom.state }} and Brightness: {{ states.input_slider.bedroom_brightness.state }}'
    - service: light.turn_on
      data_template:
        entity_id: group.bedroom_lights
        brightness: '{{ states.input_slider.bedroom_brightness.state | int }}'
        profile: "{{ states.input_select.scene_bedroom.state | lower }}"

- alias: Bedroom Lights - Input Select Turn Off
  trigger:
    - platform: state
      entity_id: input_select.scene_bedroom
      to: 'OFF'
  action:
    - service: script.turn_on
      entity_id: script.bedroom_lights_off
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_bedroom
        option: 'OFF'