- alias: "Bedroom Lights Voice Change On"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/bedroom/lights_on
  action:
    service: script.turn_on
    entity_id: script.bedroom_lights_on

- alias: "Bedroom Lights Voice Change Off"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/bedroom/lights_off
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_bedroom
        option: 'OFF'

- alias: "Bedroom Lights Voice Change Color"
  hide_entity: true
  trigger:
    - platform: mqtt
      topic: voice/bedroom/lights_color
    - platform: mqtt
      topic: voice/bedroom/lights_scene
  action:
    - service: script.notify_kodi_frontends
      data:
        message: 'Changing Color of Bedroom Lights to {{ trigger.payload }}'
    - service: input_select.select_option
      data_template:
        entity_id: input_select.scene_bedroom
        option: "{{ trigger.payload | title }}"

- alias: "Bedroom Lights Voice Dim"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/bedroom/lights_adjust
    payload: 'dim'
  action:
    service: light.turn_on
    data_template:
      brightness: "{{ states.light.right_front.brightness | float - 100 }}"
      entity_id: group.bedroom_lights

- alias: "Bedroom Lights Voice Bright"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/bedroom/lights_adjust
    payload: 'bright'
  action:
    service: light.turn_on
    data_template:
      brightness: "{{ states.light.right_front.brightness | float + 100 }}"
      entity_id: group.bedroom_lights

#- alias: "Bedroom Lights Invert"
#  hide_entity: true
#  trigger:
#    platform: mqtt
#    topic: remote/bedroom/lights_invert
#  action:
#    service: script.turn_on
#    entity_id: script.light_off_notify_righteye


- alias: Bedroom Lights - Adjust Brightness
  trigger:
    platform: state
    entity_id: input_slider.bedroom_brightness
  action:
    - service: light.turn_on
      data_template:
        entity_id: group.bedroom_lights
        brightness: '{{ trigger.to_state.state | int }}'

- alias: Bedroom Lights - Color and Brightness Slider
  trigger:
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Blue'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Red'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Pink'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Orange'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'White'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Purple'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Green'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Teal'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Aqua'
  action:
    - service: script.notify_kodi_frontends
      data_template:
        message: 'Changing Bedroom Lights to Scene: {{ states.input_select.scene_bedroom.state }} and Brightness: {{ states.input_slider.bedroom_brightness.state }}'
    - service: light.turn_on
      data_template:
        entity_id: group.bedroom_lights
        brightness: '{{ states.input_slider.bedroom_brightness.state | int }}'
        profile: "{{ states.input_select.scene_bedroom.state | lower }}"

- alias: Bedroom Lights - Scene and Brightness Slider
  trigger:
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Normal'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Movie'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Concentrate'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Energize'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Reading'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Relax'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Romantic'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Warm'
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'Stretch'
  action:
    - service: script.notify_kodi_frontends
      data_template:
        message: 'Changing Bedroom Lights to Scene: {{ states.input_select.scene_bedroom.state }} and Brightness: {{ states.input_slider.bedroom_brightness.state }}'
    - service: light.turn_on
      data_template:
        entity_id: group.bedroom_lights
        brightness: '{{ states.input_slider.bedroom_brightness.state | int }}'
        profile: "{{ states.input_select.scene_bedroom.state | lower }}"

- alias: Bedroom Lights - Off
  trigger:
    - platform: state
      entity_id: input_select.scene_bedroom
      state: 'OFF'
  action:
    - service: script.turn_on
      entity_id: script.bedroom_lights_off
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_bedroom
        option: 'OFF'