- alias: "Homeassistant Startup - Dim On"
  hide_entity: true
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: time
    after: '18:00:00'
    before: '07:01:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bathroom_light_dim

- alias: "Homeassistant Startup - Dim On"
  hide_entity: true
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: time
    after: '07:01:00'
    before: '18:00:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bathroom_light_dim