- alias: "Kitchen Motion Detection On"
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_9_10
    to: '8'
  action:
    service: script.turn_on
    entity_id: script.kitchen_motion_on

- alias: "Kitchen Motion Detection Off"
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_9_10
    to: '0'
  action:
    service: script.turn_on
    entity_id: script.kitchen_timer_off