- alias: Kitchen Lights - Input Select Change Color
  trigger:
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Blue'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Red'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Pink'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Orange'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'White'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Purple'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Green'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Teal'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Aqua'
  action:
    - service: script.notify_kodi_frontends
      data_template:
        message: 'Changing Kitchen Lights to Scene: {{ states.input_select.scene_kitchen.state }} and Brightness: {{ states.input_slider.kitchen_brightness.state }}'
    - service: light.turn_on
      data_template:
        entity_id: group.kitchen_lights
        brightness: '{{ states.input_slider.kitchen_brightness.state | int }}'
        profile: "{{ states.input_select.scene_kitchen.state | lower }}"

- alias: Kitchen Lights - Input Select Change Scene
  trigger:
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Normal'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Movie'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Concentrate'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Energize'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Reading'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Relax'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Romantic'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Warm'
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'Stretch'
  action:
    - service: script.notify_kodi_frontends
      data_template:
        message: 'Changing Kitchen Lights to Scene: {{ states.input_select.scene_kitchen.state }} and Brightness: {{ states.input_slider.kitchen_brightness.state }}'
    - service: light.turn_on
      data_template:
        entity_id: group.kitchen_lights
        brightness: '{{ states.input_slider.kitchen_brightness.state | int }}'
        profile: "{{ states.input_select.scene_kitchen.state | lower }}"

- alias: Kitchen Lights - Input Select Turn Off
  trigger:
    - platform: state
      entity_id: input_select.scene_kitchen
      state: 'OFF'
  action:
    - service: script.turn_on
      entity_id: script.kitchen_lights_off
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_kitchen
        option: 'OFF'