- alias: "Kitchen Motion Detection On"
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_kitchen_burglar
    to: '8'
  condition:
    condition: state
    entity_id: input_boolean.enable_kitchen_automation
    state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.kitchen_lights_on
    - service: timer.start
      entity_id: timer.kitchen_timer

- alias: "Kitchen Timer Finished (Motion Detected)"
  initial_state: 'true'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kitchen_timer
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.enable_kitchen_automation
        state: 'on'
      - condition: state
        entity_id: sensor.aeotec_zw100_multisensor_kitchen_burglar
        state: '8'
  action:
    - service: timer.start
      data:
        entity_id: timer.kitchen_timer

# bug: what about if the burglar sensor is tampered with?
- alias: "Kitchen Timer Finished (Motion Not Detected)"
  initial_state: 'true'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kitchen_timer
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.enable_kitchen_automation
        state: 'on'
      - condition: state
        entity_id: sensor.aeotec_zw100_multisensor_kitchen_burglar
        state: '0'
  action:
    - service: script.turn_on
      data:
        entity_id: script.kitchen_lights_off
