- alias: "Kitchen Lights Voice Change On"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/kitchen/lights_on
  action:
    service: script.turn_on
    entity_id: script.kitchen_light_on

- alias: "Kitchen Lights Voice Change Off"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/kitchen/lights_off
  action:
    - service: script.turn_on
      entity_id: script.kitchen_light_off
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_kitchen
        option: 'OFF'

- alias: "Kitchen Lights Voice Change Color"
  hide_entity: true
  trigger:
    - platform: mqtt
      topic: voice/kitchen/lights_color
    - platform: mqtt
      topic: voice/kitchen/lights_scene
  action:
    - service: script.notify_kodi_frontends
      data:
        message: "Changing Color of Kitchen Lights to {{ trigger.payload }}"
    - service: input_select.select_option
      data_template:
        entity_id: input_select.scene_kitchen
        option: "{{ trigger.payload | title }}"

- alias: "Kitchen Lights Voice Dim"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/kitchen/lights_adjust
    payload: 'dim'
  action:
    service: light.turn_on
    data_template:
      brightness: "{{ states.light.kitchen_1.brightness | float - 100 }}"
      entity_id: group.kitchen_lights

- alias: "Kitchen Lights Voice Bright"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/kitchen/lights_adjust
    payload: 'bright'
  action:
    service: light.turn_on
    data_template:
      brightness: "{{ states.light.kitchen_1.brightness | float + 100 }}"
      entity_id: group.kitchen_lights

- alias: Kitchen Lights - Adjust Brightness
  trigger:
    platform: state
    entity_id: input_slider.bar_brightness
  action:
    - service: light.turn_on
      data_template:
        entity_id: group.kitchen_lights
        brightness: '{{ trigger.to_state.state | int }}'

- alias: Kitchen Lights - Scene and Brightness Slider
  trigger:
    platform: state
    entity_id: input_select.scene_kitchen
  action:
    - service: script.notify_kodi_frontends
      data_template:
        message: 'Changing Kitchen Lights to Scene: {{ states.input_select.scene_kitchen.state }} and Brightness: {{ states.input_slider.kitchen_brightness.state }}'
    - service: light.turn_on
      data_template:
        entity_id: group.kitchen_lights
        brightness: '{{ states.input_slider.kitchen_brightness.state | int }}'
        profile: "{{ states.input_select.scene_kitchen.state | lower }}"