- alias: "Kitchen Lights - Voice Change On"
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: voice/kitchen/lights_on
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_kitchen
        option: 'White'

- alias: "Kitchen Lights - Voice Change Off"
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: voice/kitchen/lights_off
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_kitchen
        option: 'OFF'

- alias: "Kitchen Lights Voice - Change Color/Scene"
  initial_state: 'true'
  trigger:
    - platform: mqtt
      topic: voice/kitchen/lights_color
    - platform: mqtt
      topic: voice/kitchen/lights_scene
  action:
    - service: script.notify_kodi_frontends
      data:
        message: "Changing Color of Kitchen Lights to {{ trigger.payload }}"
    - service: input_select.select_option
      data_template:
        entity_id: input_select.scene_kitchen
        option: "{{ trigger.payload | title }}"

- alias: "Kitchen Lights - Voice Change Dim"
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: voice/kitchen/lights_adjust
    payload: 'dim'
  action:
    service: light.turn_on
    data_template:
      brightness: "{{ states.light.kitchen_1.brightness | float - 100 }}"
      entity_id: group.kitchen_lights

- alias: "Kitchen Lights - Voice Change Bright"
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: voice/kitchen/lights_adjust
    payload: 'bright'
  action:
    service: light.turn_on
    data_template:
      brightness: "{{ states.light.kitchen_1.brightness | float + 100 }}"
      entity_id: group.kitchen_lights
