- alias: "Kitchen Motion Detection Nightlight On"
  trigger:
    platform: state
    entity_id: binary_sensor.__sensor_5_0
    from: 'off'
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_bright_on

- alias: "Kitchen Motion Detection Off"
  trigger:
    platform: state
    entity_id: binary_sensor.__sensor_5_0
    from: 'on'
    to: 'off'
  action:
    service: light.turn_off
    entity_id: group.kitchen_lights