- alias: Kitchen Lights - Adjust Brightness
  trigger:
    platform: state
    entity_id: input_slider.bar_brightness
  action:
    - service: light.turn_on
      data_template:
        entity_id: group.kitchen_lights
        brightness: '{{ trigger.to_state.state | int }}'