- alias: "Kitchen Motion Detection On"
  trigger:
    platform: state
    entity_id: binary_sensor.__sensor_5_0
    from: 'off'
    to: 'on'
  action:
    service: script.turn_on
    entity_id: script.kitchen_motion_on

- alias: "Kitchen Motion Detection Off"
  trigger:
    platform: state
    entity_id: binary_sensor.__sensor_5_0
    from: 'on'
    to: 'off'
  action:
    service: script.turn_on
    entity_id: script.kitchen_off_timer