- alias: "Kitchen Lights Voice Change On"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/kitchen/lights_on
  action:
    service: script.turn_on
    entity_id: script.kitchen_light_on

- alias: "Kitchen Lights Voice Change Off"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/kitchen/lights_off
  action:
    service: script.turn_on
    entity_id: script.kitchen_light_off

- alias: "Kitchen Lights Voice Change Color"
  hide_entity: true
  trigger:
    - platform: mqtt
      topic: voice/kitchen/lights_color
    - platform: mqtt
      topic: voice/kitchen/lights_scene
  action:
    - service: script.turn_on
      data:
        entity_id: script_notify_kodi_frontends
        variables:
          message: "Changing Color of Kitchen Lights to {{ trigger.payload }}"
    - service: light.turn_on
      data_template:
        profile: "{{ trigger.payload }}"
        entity_id: group.kitchen_lights

- alias: "Kitchen Lights Voice Dim"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/kitchen/lights_adjust
    payload: 'dim'
  action:
    service: light.turn_on
    data_template:
      brightness: "{{ states.light.kitchen_1.brightness | float - 100 }}"
      entity_id: group.kitchen_lights

- alias: "Kitchen Lights Voice Bright"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/kitchen/lights_adjust
    payload: 'bright'
  action:
    service: light.turn_on
    data_template:
      brightness: "{{ states.light.kitchen_1.brightness | float + 100 }}"
      entity_id: group.kitchen_lights

- alias: Kitchen Lights - Adjust Brightness
  trigger:
    platform: state
    entity_id: input_slider.bar_brightness
  action:
    - service: light.turn_on
      data_template:
        entity_id: group.kitchen_lights
        brightness: '{{ trigger.to_state.state | int }}'