- alias: Kitchen Lights - Input Select Change Color
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Blue'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Red'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Pink'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Orange'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'White'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Purple'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Green'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Teal'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Aqua'
  action:
    - service: light.turn_on
      data_template:
        entity_id: group.kitchen_lights
        brightness: '{{ states.input_number.kitchen_brightness.state | int }}'
        profile: "{{ states.input_select.scene_kitchen.state | lower }}"

- alias: Kitchen Lights - Input Select Change Scene
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Normal'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Movie'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Concentrate'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Energize'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Reading'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Relax'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Romantic'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Warm'
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'Stretch'
  action:
    - service: light.turn_on
      data_template:
        entity_id: group.kitchen_lights
        brightness: '{{ states.input_number.kitchen_brightness.state | int }}'
        profile: "{{ states.input_select.scene_kitchen.state | lower }}"

- alias: Kitchen Lights - Input Select Turn Off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: input_select.scene_kitchen
      to: 'OFF'
  action:
    - service: script.turn_on
      entity_id: script.kitchen_lights_off
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_kitchen
        option: 'OFF'
