- alias: "Bedroom Kodi Play 000sexysongs"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: kodi/sexy
  action:
    service: media_player.play_media
    data:
      entity_id: media_player.kodi_bedroom_righteye
      media_content_id: "nfs://brain/mnt/mass_storage/storage/MP3s/000sexysongs"
      media_content_type: "directory"