- alias: "Lamp Voice Change On"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/lamp/lights_on
  action:
    service: light.turn_on
    entity_id: light.lamp

- alias: "Lamp Voice Change Off"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/lamp/lights_off
  action:
    service: light.turn_off
    entity_id: light.lamp

- alias: "Lamp Voice Change Color"
  hide_entity: true
  trigger:
    - platform: mqtt
      topic: voice/lamp/lights_color
    - platform: mqtt
      topic: voice/lamp/lights_scene
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Changing Color of Lamp"
    - service: light.turn_on
      data_template:
        profile: "{{ trigger.payload }}"
        entity_id: light.lamp