- alias: "Lamp Voice Change On"
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: voice/lamp/lights_on
  action:
    service: light.turn_on
    entity_id: light.lamp

- alias: "Lamp Voice Change Off"
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: voice/lamp/lights_off
  action:
    service: light.turn_off
    entity_id: light.lamp

- alias: "Lamp Voice Change Color"
  initial_state: 'true'
  trigger:
    - platform: mqtt
      topic: voice/lamp/lights_color
    - platform: mqtt
      topic: voice/lamp/lights_scene
  action:
    - service: light.turn_on
      data_template:
        profile: "{{ trigger.payload }}"
        entity_id: light.lamp
