- alias: "Motion Detection Nightlight (Kitchen Light Off)"
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_livingroom_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.livingroom_lights
        state: 'off'
      - condition: state
        entity_id: input_boolean.enable_livingroom_automation
        state: 'on'
      - condition: state
        entity_id: light.kitchen_1
        state: 'on'
  action:
    service: script.turn_on
    entity_id: script.timed_nightlight_without_kitchen

- alias: "Motion Detection Nightlight (Kitchen Light On)"
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_livingroom_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.livingroom_lights
        state: 'off'
      - condition: state
        entity_id: input_boolean.enable_livingroom_automation
        state: 'on'
      - condition: state
        entity_id: light.kitchen_1
        state: 'off'
  action:
    service: script.turn_on
    entity_id: script.timed_nightlight_with_kitchen

- alias: "Motion Detection Nightlight (Kitchen Light Only)"
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_livingroom_burglar
    to: '8'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.livingroom_lights
        state: 'on'
      - condition: state
        entity_id: input_boolean.enable_livingroom_automation
        state: 'on'
      - condition: state
        entity_id: light.kitchen_1
        state: 'off'    
  action:
    service: script.turn_on
    entity_id: script.timed_nightlight_only_kitchen

- alias: Livingroom Lights - Adjust Brightness
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: input_number.livingroom_brightness
  action:
    - service: light.turn_on
      data_template:
        entity_id: group.livingroom_lights
        brightness: '{{ trigger.to_state.state | int }}'

- alias: "Livingroom Timer Finished"
  initial_state: 'true'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.livingroom_timer
  action:
    - service: script.turn_on
      data:
        entity_id: script.livingroom_lights_off
