- alias: Livingroom Lights - Input Select Change Color
  trigger:
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Blue'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Red'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Pink'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Orange'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'White'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Purple'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Green'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Teal'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Aqua'
  action:
    - service: script.notify_kodi_frontends
      data_template:
        message: 'Changing Livingroom Lights to Scene: {{ states.input_select.scene_livingroom.state }} and Brightness: {{ states.input_number.livingroom_brightness.state }}'
    - service: light.turn_on
      data_template:
        entity_id: group.livingroom_lights
        brightness: '{{ states.input_number.livingroom_brightness.state | int }}'
        profile: "{{ states.input_select.scene_livingroom.state | lower }}"

- alias: Livingroom Lights - Input Select Change Scene
  trigger:
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Normal'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Movie'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Concentrate'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Energize'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Reading'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Relax'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Romantic'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Warm'
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'Stretch'
  action:
    - service: script.notify_kodi_frontends
      data_template:
        message: 'Changing Livingroom Lights to Scene: {{ states.input_select.scene_livingroom.state }} and Brightness: {{ states.input_number.livingroom_brightness.state }}'
    - service: light.turn_on
      data_template:
        entity_id: group.livingroom_lights
        brightness: '{{ states.input_number.livingroom_brightness.state | int }}'
        profile: "{{ states.input_select.scene_livingroom.state | lower }}"

- alias: Livingroom Lights - Input Select Turn Off
  trigger:
    - platform: state
      entity_id: input_select.scene_livingroom
      to: 'OFF'
  action:
    - service: script.turn_on
      entity_id: script.livingroom_lights_off
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_livingroom
        option: 'OFF'