- alias: "Livingroom Lights - Voice Change On"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/livingroom/lights_on
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_livingroom
        option: 'White'

- alias: "Livingroom Lights - Voice Change Off"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/livingroom/lights_off
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_livingroom
        option: 'OFF'

- alias: "Livingroom Lights - Voice Change Color/Scene"
  hide_entity: true
  trigger:
    - platform: mqtt
      topic: voice/livingroom/lights_color
    - platform: mqtt
      topic: voice/livingroom/lights_scene
  action:
    - service: script.notify_kodi_frontends
      data:
        message: "Changing Color of Livingroom Lights to {{ trigger.payload }}"
    - service: input_select.select_option
      data_template:
        entity_id: input_select.scene_livingroom
        option: "{{ trigger.payload | title }}"

- alias: "Livingroom Lights - Voice Change Dim"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/livingroom/lights_adjust
    payload: 'dim'
  action:
    service: light.turn_on
    data_template:
#      entity_id: group.livingroom_lights
      entity_id:
        - light.lamp
#        - light.lightstrip_1
      brightness: >
        {% if states('light.lamp.brightness') | int > 200 %}
          150
        {% else %}
          50
        {% endif %}

- alias: "Livingroom Lights - Voice Change Bright"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/livingroom/lights_adjust
    payload: 'bright'
  action:
    service: light.turn_on
    data_template:
#      entity_id: group.livingroom_lights
      entity_id:
        - light.lamp
 #       - light.lightstrip_1
      brightness: >
        {% if states('light.lamp.brightness') | int < 51 %}
          150
        {% else %}
          254
        {% endif %}