- alias: "Livingroom Lights Voice Change On"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/livingroom/lights_on
  action:
    service: script.turn_on
    entity_id: script.livingroom_lights_on

- alias: "Livingroom Lights Voice Change Off"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/livingroom/lights_off
  action:
    service: script.turn_on
    entity_id: script.livingroom_lights_off

- alias: "Livingroom Lights Voice Change Color"
  hide_entity: true
  trigger:
    - platform: mqtt
      topic: voice/livingroom/lights_color
    - platform: mqtt
      topic: voice/livingroom/lights_scene  
  action:
    - service: script.turn_on
      data:
        entity_id: script_notify_kodi_frontends
        variables:
          message: "Changing Color of Livingroom Lights to {{ trigger.payload }}"
    - service: light.turn_on
      data_template:
        profile: "{{ trigger.payload }}"
        entity_id: group.livingroom_lights
    - service: input_select.select_value
      data_template:
        entity_id: input_select.scene_livingroom
        value: '{{ trigger.payload }}'

- alias: "Livingroom Lights Voice Dim"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/livingroom/lights_adjust
    payload: 'dim'
  action:
    service: light.turn_on
    data_template:
#      entity_id: group.livingroom_lights
      entity_id:
        - light.lamp
#        - light.lightstrip_1
      brightness: >
        {% if states('light.lamp.brightness') | int > 200 %}
          150
        {% else %}
          50
        {% endif %}

- alias: "Livingroom Lights Voice Bright"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/livingroom/lights_adjust
    payload: 'bright'
  action:
    service: light.turn_on
    data_template:
#      entity_id: group.livingroom_lights
      entity_id:
        - light.lamp
 #       - light.lightstrip_1
      brightness: >
        {% if states('light.lamp.brightness') | int < 51 %}
          150
        {% else %}
          254
        {% endif %}