- alias: "Strip Voice Change On"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/strip/lights_on
  action:
    service: light.turn_on
    entity_id: light.lightstrip

- alias: "Strip Voice Change Off"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/strip/lights_off
  action:
    service: light.turn_off
    entity_id: light.lightstrip

- alias: "Strip Voice Change Color"
  hide_entity: true
  trigger:
    - platform: mqtt
      topic: voice/strip/lights_color
    - platform: mqtt
      topic: voice/strip/lights_scene
  action:
    - service: script.turn_on
      data:
        entity_id: script_notify_kodi_frontends
        variables:
          message: "Changing Color of Strip"
    - service: light.turn_on
      data_template:
        profile: "{{ trigger.payload }}"
        entity_id: light.lightstrip