- alias: "Track Voice Change On"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/track/lights_on
  action:
    service: switch.turn_on
    entity_id: switch.track_lighting_switch_switch

- alias: "Track Voice Change Off"
  hide_entity: true
  trigger:
    platform: mqtt
    topic: voice/track/lights_off
  action:
    service: switch.turn_off
    entity_id: switch.track_lighting_switch_switch