- alias: 'WakeUp Light Bedroom'
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.wakeup
        state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.wakeup_weekends
            state: 'on'
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
      - condition: template
        value_template: '{{ now().strftime("%H:%M") == states.sensor.wakeup_start_time_lights.state }}'
  action:
    service: script.wakeup_bedroom

- alias: Sleep Routine
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: input_boolean.sleep
    to: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Sleep Routine Started!"
#    - service: media_player.play_media
#      data:
#        entity_id: media_player.righteye_mpd
#        media_content_type: playlist
#        media_content_id: sleep
#    - service: media_player.volume_set
#      data:
#        entity_id: media_player.righteye_mpd
#        volume_level: 0.40
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_bedroom
        option: 'OFF'

- alias: Cancel Sleep Routine
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: input_boolean.sleep
    to: 'off'
  action:
    - service: script.turn_on
      data:
        entity_id: script.notify_kodi_frontends
        variables:
          message: "Sleep Routine Cancelled!"
#    - service: media_player.media_stop
#      data:
#        entity_id: media_player.righteye_mpd