- platform: template
  sensors:
    livingroom_motion:
      friendly_name: "Motion"
      value_template: >-
        {% if states.sensor.aeotec_zw100_multisensor_6_burglar_3_10.state == '8' %}
          Detected
        {% elif states.sensor.aeotec_zw100_multisensor_6_burglar_3_10.state == '3' %}
          Tampered With
        {% elif states.sensor.aeotec_zw100_multisensor_6_burglar_3_10.state == '0' %}
          On Standby
        {% endif %}

    bathroom_motion:
      friendly_name: "Motion"
      value_template: >-
        {% if states.sensor.aeotec_zw100_multisensor_6_burglar_4_10.state == '8' %}
          Detected
        {% elif states.sensor.aeotec_zw100_multisensor_6_burglar_4_10.state == '3' %}
          Tampered With
        {% elif states.sensor.aeotec_zw100_multisensor_6_burglar_4_10.state == '0' %}
          On Standby
        {% endif %}

    bathroom_motion_early:
      friendly_name: "Motion"
      value_template: >-
        {% if states.sensor.aeotec_zw100_multisensor_6_burglar_8_10.state == '8' %}
          Detected
        {% elif states.sensor.aeotec_zw100_multisensor_6_burglar_8_10.state == '3' %}
          Tampered With
        {% elif states.sensor.aeotec_zw100_multisensor_6_burglar_8_10.state == '0' %}
          On Standby
        {% endif %}

    kitchen_motion:
      friendly_name: "Motion"
      value_template: >-
        {% if states.sensor.aeotec_zw100_multisensor_6_burglar_9_10.state == '8' %}
          Detected
        {% elif states.sensor.aeotec_zw100_multisensor_6_burglar_9_10.state == '3' %}
          Tampered With
        {% elif states.sensor.aeotec_zw100_multisensor_6_burglar_9_10.state == '0' %}
          On Standby
        {% endif %}