- platform: template
  sensors:
    Bed_Pressure:
      friendly_name: "In Bed"
      value_template: >-
        {% if is_state("binary_sensor.__sensor_10_0", "On") %}
          Out
        {% elif is_state("binary_sensor.__sensor_10_0", "Off") %}
          In
        {% else %}
          Unknown
        {% endif %}