- platform: template
  sensors:
    bed_pressure_left:
      friendly_name: "In Bed"
      value_template: >-
        {% if is_state("binary_sensor.bed_pressure_left_sensor", "on") %}
          No
        {% elif is_state("binary_sensor.bed_pressure_left_sensor", "off") %}
          Yes
        {% else %}
          Unknown
        {% endif %}
    bed_pressure_right:
      friendly_name: "In Bed"
      value_template: >-
        {% if is_state("binary_sensor.bed_pressure_right_sensor", "on") %}
          No
        {% elif is_state("binary_sensor.bed_pressure_right_sensor", "off") %}
          Yes
        {% else %}
          Unknown
        {% endif %}