- platform: template
  sensors:
    bed_pressure:
      friendly_name: "In Bed"
      value_template: >-
        {% if is_state("binary_sensor.bed_pressure_sensor_sensor", "on") %}
          No
        {% elif is_state("binary_sensor.bed_pressure_sensor_sensor", "off") %}
          Yes
        {% else %}
          Unknown
        {% endif %}