- platform: yweather
  woeid: 12798510
  forecast: 3
  name: Portland
  monitored_conditions:
    - weather
    - weather_current
    - temp_min
    - temp_max
    - wind_speed
    - pressure
    - visibility
    - humidity
    - temperature