sensor.aeotec_zw100_multisensor_6_burglar_3:
#  icon: mdi:door
  friendly_name: "Livingroom Motion"

sensor.aeotec_zw100_multisensor_6_luminance_3:
  friendly_name: "Bedroom Luminance"

# sensor.aeotec_zw100_multisensor_6_relative_humidity_3
# sensor.aeotec_zw100_multisensor_6_temperature_3
# sensor.aeotec_zw100_multisensor_6_ultraviolet_3

sensor.aeotec_zw100_multisensor_6_burglar_4:
#  icon: mdi:door
  friendly_name: "Kitchen Motion"

sensor.aeotec_zw100_multisensor_6_luminance_4:
  friendly_name: "Kitchen Luminance"

# sensor.aeotec_zw100_multisensor_6_relative_humidity_4
# sensor.aeotec_zw100_multisensor_6_temperature_4
# sensor.aeotec_zw100_multisensor_6_ultraviolet_4

binary_sensor.__sensor_5:
  friendly_name: "Bathroom Motion"