homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret homeassistant_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 199
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

sensor: !include_dir_merge_list sensors/
light: !include devices/lights.yaml
media_player: !include_dir_list devices/kodi
automation: !include_dir_merge_list automation/
notify: !include_dir_list notify/
script: !include_dir_merge_named scripts/
group: !include groups.yaml
scene: !include scenes.yaml
zwave: !include zwave.yaml
logger: !include logger.yaml
history: !include history.yaml
input_boolean: !include input_boolean.yaml
input_slider: !include input_slider.yaml
input_select: !include input_select.yaml

switch:
  - platform: thinkingcleaner
  - platform: tplink
    host: 192.168.5.10

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
# Uncomment this to add a password (recommended!)
  api_password: !secret http_password
#  ssl_certificate: /fullchain.pem
#  ssl_key: /privkey.pem

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:

# Track the sun
#sun:

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_secret

climate:
  platform: nest

#device_tracker:
#  - platform: nmap_tracker
#    hosts: 192.168.2.1/29
#    exclude:
#    - 192.168.2.0
#    - 192.168.2.4
#    - 192.168.2.5
#    - 192.168.2.6
#    - 192.168.2.7
#    consider_home: 180
##    track_new_devices: yes
#    track_new_devices: no

mqtt:
  broker: mosca
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: !secret dyson_language
  devices:
    - device_id: !secret dyson_device_id_1
      device_ip: !secret dyson_device_ip_1

graphite:
  host: !secret graphite_ip