homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret homeassistant_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 199
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

timer: !include timers.yaml
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
hue: !include devices/hue.yaml
media_player: !include_dir_list media_player/
automation: !include_dir_merge_list automation/
notify: !include_dir_list notify/
script: !include_dir_merge_named scripts/
group: !include groups.yaml
scene: !include scenes.yaml
zwave: !include zwave.yaml
logger: !include logger.yaml
history: !include history.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
input_select: !include input_select.yaml

switch: !include_dir_merge_list switch/

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
# Uncomment this to add a password (recommended!)
  trusted_networks:
    - 192.168.2.1
    - 127.0.0.1
    - 192.168.0.0/21
  ip_ban_enabled: false
#  ssl_certificate: /fullchain.pem
#  ssl_key: /privkey.pem

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Logbook settings
logbook: !include logbook.yaml

# Track the sun
#sun:

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_secret

climate:
  platform: nest

panel_iframe:
  temp_over_time:
    title: 'Temperature'
    url: 'http://grafana.thesteamedcrab.com:3000/dashboard/db/homeassistant-temperature?orgId=1&from=1498971478579&to=1499057878579'
  kitchen_motion:
    title: 'Kitchen Motion'
    url: 'http://grafana.thesteamedcrab.com:3000/dashboard/db/homeassistant-kitchen-motion?refresh=5s&orgId=1&from=1499047509780&to=1499058309780'

#device_tracker:
#  - platform: nmap_tracker
#    hosts: 192.168.2.1/29
#    exclude:
#    - 192.168.2.0
#    - 192.168.2.4
#    - 192.168.2.5
#    - 192.168.2.6
#    - 192.168.2.7
#    consider_home: 180
##    track_new_devices: yes
#    track_new_devices: no

#device_tracker:
#  - platform: owntracks

zone:
  name: Home
  latitude: 45.528472
  longitude: -122.681457
  radius: 50
  icon: mdi:account-multiple

mqtt:
  broker: mosca
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: !secret dyson_language
  devices:
    - device_id: !secret dyson_device_id_1
      device_ip: !secret dyson_device_ip_1

graphite:
  host: !secret graphite_ip

plant:
  fern:
    sensors:
      moisture: sensor.fern_moisture
      battery: sensor.fern_battery
      temperature: sensor.fern_temperature
      conductivity: sensor.fern_conductivity
      brightness: sensor.fern_brightness
    min_moisture: 15
    max_moisture: 60
    min_battery: 15
    min_conductivity: 350
    min_temperature: 50
    max_temperature: 89    
  palm:
    sensors:
      moisture: sensor.palm_moisture
      battery: sensor.palm_battery
      temperature: sensor.palm_temperature
      conductivity: sensor.palm_conductivity
      brightness: sensor.palm_brightness
    min_moisture: 15
    max_moisture: 60
    min_battery: 15
    min_conductivity: 350
    min_temperature: 50
    max_temperature: 89    
  zz:
    sensors:
      moisture: sensor.zz_moisture
      battery: sensor.zz_battery
      temperature: sensor.zz_temperature
      conductivity: sensor.zz_conductivity
      brightness: sensor.zz_brightness
    min_moisture: 15
    max_moisture: 60
    min_battery: 15
    min_conductivity: 350
    min_temperature: 50
    max_temperature: 89    
  pothos1:
    sensors:
      moisture: sensor.pothos1_moisture
      battery: sensor.pothos1_battery
      temperature: sensor.pothos1_temperature
      conductivity: sensor.pothos1_conductivity
      brightness: sensor.pothos1_brightness
    min_moisture: 15
    max_moisture: 60
    min_battery: 15
    min_conductivity: 350
    min_temperature: 50
    max_temperature: 89    
  pothos2:
    sensors:
      moisture: sensor.pothos2_moisture
      battery: sensor.pothos2_battery
      temperature: sensor.pothos2_temperature
      conductivity: sensor.pothos2_conductivity
      brightness: sensor.pothos2_brightness
    min_moisture: 15
    max_moisture: 60
    min_battery: 15
    min_conductivity: 350
    min_temperature: 50
    max_temperature: 89
  petra:
    sensors:
      moisture: sensor.petra_moisture
      battery: sensor.petra_battery
      temperature: sensor.petra_temperature
      conductivity: sensor.petra_conductivity
      brightness: sensor.petra_brightness
    min_moisture: 15
    max_moisture: 60
    min_battery: 15
    min_conductivity: 350
    min_temperature: 41
    max_temperature: 89
  donkey:
    sensors:
      moisture: sensor.donkey_moisture
      battery: sensor.donkey_battery
      temperature: sensor.donkey_temperature
      conductivity: sensor.donkey_conductivity
      brightness: sensor.donkey_brightness
    min_moisture: 15
    max_moisture: 60
    min_battery: 15
    min_conductivity: 350
    min_temperature: 41
    max_temperature: 89    