title: Tanner Place
views:
  - title: Home
    badges: []
    path: default_view
    cards:
      - title: Bedroom
        type: entities
        show_header_toggle: false
        entities:
          - input_select.scene_bedroom
          - input_number.bedroom_brightness
          - group.bedroom_lights
          - switch.my_smart_plug_mini
          - sensor.bed_pressure_left
          - sensor.bed_pressure_right
          - switch.sonoff_100044903f
      - title: Livingroom
        type: entities
        show_header_toggle: false
        entities:
          - input_select.scene_livingroom
          - input_number.livingroom_brightness
          - group.livingroom_lights
          - sensor.livingroom_motion
          - sensor.aeotec_zw100_multisensor_livingroom_luminance
          - switch.fireplace_switch
          - sensor.roomba_state
      - title: Kitchen
        type: entities
        show_header_toggle: false
        entities:
          - input_select.scene_kitchen
          - input_number.bar_brightness
          - group.kitchen_lights
          - sensor.kitchen_motion
      - title: Bathroom
        type: entities
        show_header_toggle: false
        entities:
          - input_select.scene_bathroom
          - input_number.bathroom_brightness
          - group.bathroom_lights
          - switch.sonoff_10006b80c3
          - sensor.bathroom_motion
          - sensor.aeotec_zw100_multisensor_bathroom_relative_humidity
          - binary_sensor.bathroom_high_humidity
          - sensor.aeotec_zw100_multisensor_toilet_relative_humidity
          - binary_sensor.toilet_high_humidity
  - title: Location
    type: entities
    path: location
    badges: []
    show_header_toggle: false
    cards:
      - entities:
        - device_tracker.galaxy_s10_thesteamedcrab_com
        - device_tracker.renee_android_thesteamedcrab_com
        - device_tracker.d4_53_83_94_4a_f2
        - device_tracker.14_56_8e_44_09_86
        type: entities
  - title: Wakeup Time
    path: wakeuplight
    badges: []
    cards:
      - entities:
          - sensor.wakeup_alarm_time
          - sensor.wakeup_start_time_lights
          - sensor.wakeup_fadein_duration
        show_header_toggle: false
        type: entities
      - entities:
          - input_number.wakeup_hour
          - input_number.wakeup_minutes
          - input_number.wakeup_duration
        show_header_toggle: false
        title: Wakeup Time Settings
        type: entities
      - title: Wakeup Light Settings
        entities:
          - input_boolean.wakeup
          - input_boolean.wakeup_weekends
        show_header_toggle: false
        type: entities
  - title: Sleep
    badges: []
    cards:
      - entities:
          - input_boolean.sleep
        type: entities
    path: sleepsettings
    show_header_toggle: false
  - title: Climate
    path: climate
    badges: []
    cards:
      - title: Weather Inside
        type: entities
        show_header_toggle: false
        entities:
          - sensor.aeotec_zw100_multisensor_livingroom_temperature
          - sensor.aeotec_zw100_multisensor_livingroom_relative_humidity
      - title: Nest
        type: thermostat
        entity: climate.entrywaynest        
      - title: Weather Outside
        type: entities
        show_header_toggle: false
        entities:
          - sensor.dark_sky_summary
          - sensor.dark_sky_icon
          - sensor.dark_sky_temperature 
  - title: Sensors
    path: sensors
    badges: []
    cards:
      - entities:
          - sensor.kitchen_motion
          - sensor.aeotec_zw100_multisensor_kitchen_luminance
          - sensor.aeotec_zw100_multisensor_kitchen_relative_humidity
          - sensor.aeotec_zw100_multisensor_kitchen_temperature
          - sensor.aeotec_zw100_multisensor_kitchen_ultraviolet
        show_header_toggle: false
        title: Kitchen Sensor
        type: entities
      - entities:
          - sensor.livingroom_motion
          - sensor.aeotec_zw100_multisensor_livingroom_luminance
          - sensor.aeotec_zw100_multisensor_livingroom_relative_humidity
          - sensor.aeotec_zw100_multisensor_livingroom_temperature
          - sensor.aeotec_zw100_multisensor_livingroom_ultraviolet
        show_header_toggle: false
        title: Livingroom Sensor
        type: entities
      - entities:
          - sensor.bathroom_motion_early
          - sensor.aeotec_zw100_multisensor_bathroom_early_luminance
          - sensor.aeotec_zw100_multisensor_bathroom_early_relative_humidity
          - sensor.aeotec_zw100_multisensor_bathroom_early_temperature
          - sensor.aeotec_zw100_multisensor_bathroom_early_ultraviolet
        show_header_toggle: false
        title: Bathroom Sensor (Early)
        type: entities
      - entities:
          - sensor.bathroom_motion
          - sensor.aeotec_zw100_multisensor_bathroom_luminance
          - sensor.aeotec_zw100_multisensor_bathroom_relative_humidity
          - sensor.aeotec_zw100_multisensor_bathroom_temperature
          - sensor.aeotec_zw100_multisensor_bathroom_ultraviolet
          - binary_sensor.bathroom_high_humidity
        show_header_toggle: false
        title: Bathroom Sensor (Primary)
        type: entities
      - entities:
          - sensor.toilet_motion
          - sensor.aeotec_zw100_multisensor_toilet_luminance
          - sensor.aeotec_zw100_multisensor_toilet_relative_humidity
          - sensor.aeotec_zw100_multisensor_toilet_temperature
          - sensor.aeotec_zw100_multisensor_toilet_ultraviolet
          - binary_sensor.toilet_high_humidity
        show_header_toggle: false
        title: Toilet Sensor
        type: entities
  - title: scripts
    path: scripts
    badges: []
    cards:
      - entities:
          - script.timed_nightlight_with_kitchen
          - script.timed_nightlight_without_kitchen
          - timer.livingroom_timer
        show_header_toggle: false
        title: Livingroom
        type: entities
      - entities:
          - script.timed_nightlight_only_kitchen
          - timer.kitchen_timer
        show_header_toggle: false
        title: Kitchen
        type: entities
      - entities:
          - script.timed_bathroom_early
          - timer.bathroom_early_timer
          - script.timed_bathroom_nightlight
          - script.timed_bathroom_bright
          - timer.bathroom_timer
          - script.timed_bathroom_diffuser_on
          - script.timed_bathroom_diffuser_off
          - timer.bathroom_diffuser_timer
        show_header_toggle: false
        title: Bathroom
        type: entities
  - title: Lights
    path: lights_display    
    badges: []
    cards:
      - entities:
          - light.hallway
          - light.kitchen_1
          - light.kitchen_2
          - light.lightstrip_4
          - light.bar_light_switch_level
        show_header_toggle: false
        title: Kitchen Lights
        type: entities
      - entities:
          - light.left_back
          - light.right_back
          - light.left_front
          - light.right_front
          - light.lightstrip_3
        show_header_toggle: false
        title: Bedroom Lights
        type: entities
      - entities:
          - light.lamp
          - light.lightstrip_1
          - light.lightstrip_6
          - switch.track_lighting_switch_switch
        show_header_toggle: false
        title: Livingroom Lights
        type: entities
      - entities:
          - light.bathroom_light_switch_level
          - light.lightstrip_2
          - light.lightstrip_5
        show_header_toggle: false
        title: Bathroom Lights
        type: entities
  - title: Media Players
    path: media_players  
    badges: []
    cards:
      - entity: media_player.kodi_bedroom_righteye
        type: media-control
      - entity: media_player.kodi_livingroom_lefteye
        type: media-control
      - entity: media_player.jukebox_mpd
        type: media-control
      - entity: media_player.righteye_onkyo
        type: media-control
      - entity: media_player.lefteye_onkyo
        type: media-control
  - title: Nest
    path: nest
    cards:
      - entity: climate.entryway_nest
        type: thermostat
  - title: Roomba
    path: roomba
    badges: []
    type: entities
    cards:
      - title: Roomba
        type: entities
        show_header_toggle: false
        entities:
          - sensor.roomba_state
          - sensor.roomba_capacity
          - sensor.roomba_battery
          - switch.roomba_clean
          - switch.roomba_dock
          - switch.roomba_find
  - title: Dyson
    type: entities
    path: dyson
    cards:
      - title: Dyson (Bedroom)
        show_header_toggle: false
        type: entities
        entities:
          - sensor.purifier_cool_tower_aqi
          - sensor.purifier_cool_tower_dust
          - sensor.purifier_cool_tower_filter_life
          - sensor.purifier_cool_tower_humidity
          - sensor.purifier_cool_tower_temperature
    badges: []
  - title: Plants
    path: plants
    badges: []
    cards:
      - entity: plant.fern
        type: plant-status
      - entity: plant.palm
        type: plant-status
      - entity: plant.zz
        type: plant-status
      - entity: plant.pothos1
        type: plant-status
      - entity: plant.pothos2
        type: plant-status
      - entity: plant.petra
        type: plant-status
      - entity: plant.donkey
        type: plant-status
  - title: Battery
    path: battery
    badges: []
    cards: []
  - title: Settings
    path: settings
    badges:
      - sensor.uptime
    cards:
      - entities:
          - input_boolean.notifications_on
          - input_boolean.enable_bedroom_voice_automation
          - input_boolean.enable_bathroom_automation
          - input_boolean.enable_livingroom_automation
          - input_boolean.enable_kitchen_automation
          - input_boolean.bathroom_light_dim
        show_header_toggle: false
        title: Advanced Settings
        type: entities
      - entities:
          - input_datetime.dim_time_on
          - input_datetime.bright_time_on
        show_header_toggle: false
        title: Bathroom Bright/Dim Times
        type: entities